{{- $existing := lookup "v1" "Secret" .Release.Namespace .Values.minio.existingSecret.name }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.lokistack.storage.secret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lokistack.componentLabels" (dict "root" . "component" "loki") | nindent 4 }}
type: Opaque
stringData:
  endpoint: {{ .Values.minio.endpoint }}
  region: {{ .Values.minio.region }}
  bucketnames: {{ .Values.minio.bucketName }}
{{- if $existing }}
  access_key_id: {{ index $existing.data .Values.minio.existingSecret.userKey | b64dec }}
  access_key_secret: {{ index $existing.data .Values.minio.existingSecret.passwordKey | b64dec }}
{{- end }}
