apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hub.fullname" . }}-frontend
  labels:
    {{- include "hub.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "hub.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "hub.labels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.registry }}/{{ .Values.image.frontend }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.frontend.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.frontend.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hub.fullname" . }}-frontend
  labels:
    {{- include "hub.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "hub.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
{{- if .Values.global.routes.enabled }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "hub.fullname" . }}-frontend
  labels:
    {{- include "hub.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  to:
    kind: Service
    name: {{ include "hub.fullname" . }}-frontend
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}
