{{- if .Values.mcpSecrets.openshift.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: noc-openshift-edge-kubeconfig
  labels:
    {{- include "hub.labels" . | nindent 4 }}
type: Opaque
data:
  kubeconfig: {{ .Values.mcpSecrets.openshift.kubeconfig | b64enc | quote }}
{{- end }}
{{- if .Values.mcpSecrets.aap.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: noc-aap-secret
  labels:
    {{- include "hub.labels" . | nindent 4 }}
type: Opaque
data:
  AAP_USERNAME: {{ .Values.mcpSecrets.aap.username | b64enc | quote }}
  AAP_PASSWORD: {{ .Values.mcpSecrets.aap.password | b64enc | quote }}
{{- end }}
{{- if .Values.mcpSecrets.servicenow.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: noc-servicenow-secret
  labels:
    {{- include "hub.labels" . | nindent 4 }}
type: Opaque
data:
  SERVICENOW_API_KEY: {{ .Values.mcpSecrets.servicenow.apiKey | b64enc | quote }}
{{- end }}
