llamaStack:
  name: adnr-autorag
  distributionName: rh-dev
  distributionImage: ""
  replicas: 1
  resources:
    requests:
      cpu: 250m
      memory: 500Mi
    limits:
      cpu: "4"
      memory: 12Gi
  storage:
    size: 5Gi

inference:
  model: ""
  url: ""
  apiToken: ""
  tlsVerify: "false"
  maxTokens: "4096"

embedding:
  provider: sentence-transformers
  model: BAAI/bge-m3

postgres:
  host: pgvector
  port: "5432"
  db: postgres
  user: postgres
  passwordSecret:
    name: pgvector
    key: password

milvus:
  secret:
    name: milvus-secret
